// Tên gọi dân gian cho 99 số Lô Tô
// Vietnamese folk names for Loto numbers

export const folkNames: Record<number, string> = {
    1: "Cây nảy mầm",
    2: "Con vịt bầu",
    3: "Con cua biển",
    4: "Bốn mùa xuân hạ",
    5: "Năm ngón tay xinh",
    6: "Sáu câu vọng cổ",
    7: "Bảy ngày một tuần",
    8: "Tám tiên quá hải",
    9: "Chín nàng thơ",
    10: "Mười tám vũ khí",
    11: "Đôi đũa đẹp",
    12: "Mười hai bến nước",
    13: "Xui xẻo chi đây",
    14: "Tuổi mới lớn",
    15: "Trăng rằm tháng tám",
    16: "Mười sáu trăng tròn",
    17: "Bảy mười ngọt ngào",
    18: "Tuổi đôi tám đẹp",
    19: "Mười chín đôi mươi",
    20: "Đôi mươi tròn trịa",
    21: "Hai mốt cái tết",
    22: "Hai con vịt đẹp",
    23: "Hai ba cùng về",
    24: "Hai tư mùa hè",
    25: "Hai lăm tháng mười",
    26: "Hai sáu nàng tiên",
    27: "Hai bảy rồng bay",
    28: "Hai tám tuổi xuân",
    29: "Hai chín đôi mươi",
    30: "Ba mươi tết tà",
    31: "Ba mốt em thơ",
    32: "Ba hai đằng sau",
    33: "Ba ba rùa chạy",
    34: "Ba tư mùa hạ",
    35: "Ba lăm tháng ba",
    36: "Ba sáu thiên lý",
    37: "Ba bảy hoàng hôn",
    38: "Ba tám phát tài",
    39: "Ba chín gần bốn",
    40: "Bốn mươi tuổi hồi",
    41: "Bốn mốt mùa thu",
    42: "Bốn hai mùa hè",
    43: "Bốn ba hoa nở",
    44: "Bốn bốn tứ quý",
    45: "Con thằn lằn",
    46: "Bốn sáu phong lưu",
    47: "Bốn bảy phát lộc",
    48: "Bốn tám thần tài",
    49: "Bốn chín sắp già",
    50: "Năm mươi biết điều",
    51: "Năm mốt tựu trường",
    52: "Năm hai học hành",
    53: "Năm ba vui vẻ",
    54: "Năm tư nghỉ hè",
    55: "Năm năm quốc khánh",
    56: "Năm sáu phúc lộc",
    57: "Năm bảy may mắn",
    58: "Năm tám phát tài",
    59: "Năm chín sáu mươi",
    60: "Sáu mươi hoa giáp",
    61: "Sáu mốt nghỉ hưu",
    62: "Sáu hai dưỡng già",
    63: "Sáu ba thanh thản",
    64: "Sáu tư an nhàn",
    65: "Sáu lăm vui thú",
    66: "Sáu sáu lộc phát",
    67: "Sáu bảy sung túc",
    68: "Sáu tám phát tài",
    69: "Sáu chín uyên ương",
    70: "Bảy mươi cổ lai",
    71: "Bảy mốt tri thiên",
    72: "Bảy hai nhị thập",
    73: "Bảy ba thất thập",
    74: "Bảy tư tùng tâm",
    75: "Bảy lăm tóc bạc",
    76: "Bảy sáu phúc thọ",
    77: "Bảy bảy thất tịch",
    78: "Bảy tám phát lộc",
    79: "Bảy chín tám mươi",
    80: "Tám mươi thượng thọ",
    81: "Tám mốt sống lâu",
    82: "Tám hai bách niên",
    83: "Tám ba hạnh phúc",
    84: "Tám tư vinh hoa",
    85: "Tám lăm ông bà",
    86: "Tám sáu mạnh khỏe",
    87: "Tám bảy trường thọ",
    88: "Tám tám phát phát",
    89: "Tám chín trăm tuổi",
    90: "Chín mươi thiên thu",
    91: "Chín mốt đại thọ",
    92: "Chín hai tiên ông",
    93: "Chín ba bất tử",
    94: "Chín tư thiên niên",
    95: "Chín lăm mãi mài",
    96: "Chín sáu vạn tuế",
    97: "Chín bảy phúc lộc",
    98: "Chín tám phát tài",
    99: "Chín chín như ý",
};

/**
 * Get folk name for a number
 */
export function getFolkName(num: number): string {
    return folkNames[num] || `Số ${num}`;
}

/**
 * Get formatted display text: "Số X - Tên gọi"
 */
export function getNumberDisplay(num: number): { number: string; name: string; full: string } {
    const paddedNum = num.toString().padStart(2, '0');
    const name = getFolkName(num);
    return {
        number: paddedNum,
        name,
        full: `Số ${paddedNum} - ${name}`,
    };
}
